<RootWidget>:
	LoginScreen:
		name: "login_screen"
	SignUpScreen:
		name: "sign_up_screen"
	SignUpScreenSuccess:
		name: "sign_up_screen_success"
	ForgetPassScreen:
		name: "forget_pass_screen"
	Main:
		name: "main_screen"
	Music:
		name: "music_screen"
	Movies:
		name: "movies_screen"
	Series:
		name: "series_screen"
	Books:
		name: "books_screen"
	Places:
		name: "places_screen"
	Other:
		name: "other_screen"