<RootWidget>:
	LoginScreen:
		name: "login_screen"
	SignUpScreen:
		name: "sign_up_screen"
	SignUpScreenSuccess:
		name: "sign_up_screen_success"
	ForgetPassScreen:
		name: "forget_pass_screen"
	AboutScreen:
		name: "about_screen"
	MainScreen:
		name: "main_screen"
	MusicScreen:
		name: "music_screen"
	MoviesScreen:
		name: "movies_screen"
	SeriesScreen:
		name: "series_screen"
	BooksScreen:
		name: "books_screen"
	PlacesScreen:
		name: "places_screen"
	OtherScreen:
		name: "other_screen"