<LoginScreen>:
	## Invisible widget, a way to separate the area
	GridLayout:
		cols: 1
		GridLayout:
			cols: 1
			Label:
				text: "User Login"
			TextInput:
				hint_text: "Username"
			TextInput:
				hint_text: "Password"
				password: True
			RelativeLayout:
				Button:
					text: "Login"
			Label:
				text: ""
		GridLayout:
			cols: 2
			Button:
				text: "Forgot Password"
			Button:
				text: "Sign Up"