<LoginScreen>:
	## Invisible widget, a way to separate the area
	GridLayout:
		cols: 1
		GridLayout:
			cols: 1
			Label:
				text: "User Login"
			TextInput:
				hint_text: "Username"
			TextInput:
				hint_text: "Password"
				password: True
			Button:
				text: "Login"
				on_press: root.login()
			Label:
				text: ""
		GridLayout:
			cols: 2
			Button:
				text: "Forgot Password"
				on_press: root.forgetPass()
			Button:
				text: "Sign Up"
				on_press: root.signUp()